AUTO_RESUME: True
DATA_DIR: ''
GPUS: (0,)
LOG_DIR: log
OUTPUT_DIR: output
PRINT_FREQ: 100
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  DATASET: coco_kpt
  DATASET_TEST: coco
  FLIP: 0.5
  INPUT_SIZE: 512
  OUTPUT_SIZE: 512
  MAX_NUM_PEOPLE: 30
  MAX_ROTATION: 30
  MAX_SCALE: 1.5
  SCALE_TYPE: 'short'
  MAX_TRANSLATE: 40
  MIN_SCALE: 0.75
  NUM_JOINTS: 1

  OFFSET_RADIUS: 4
  SIGMA: 2.0
  CENTER_SIGMA: 4.0
  BG_WEIGHT: 1.0
LOSS:
  WITH_HEATMAPS_LOSS: True
  HEATMAPS_LOSS_FACTOR: 100.0
  WITH_OFFSETS_LOSS: True
  OFFSETS_LOSS_FACTOR: 3.0
MODEL:
  SPEC:
    FINAL_CONV_KERNEL: 1
    PRETRAINED_LAYERS: ['*']
    STAGES:
      NUM_STAGES: 2
      NUM_MODULES: 
      - 1
      - 1
      NUM_BRANCHES: 
      - 2
      - 3
      BLOCK: 
      - BASIC
      - BASIC
      NUM_BLOCKS:
      - [1, 1]
      - [1, 1, 1]
      NUM_CHANNELS:
      - [32, 64]
      - [32, 64, 128]
      FUSE_METHOD: 
      - SUM
      - SUM
    HEAD_HEATMAP:
      BLOCK: BASIC
      NUM_BLOCKS: 1
      NUM_CHANNELS: 32
      DILATION_RATE: 1
    HEAD_OFFSET:
      BLOCK: ADAPTIVE
      NUM_BLOCKS: 2
      NUM_CHANNELS_PERKPT: 8
      DILATION_RATE: 1
  INIT_WEIGHTS: True
  NAME: hrnet_dekr
  NUM_JOINTS: 1
  PRETRAINED: 'model/imagenet/hrnet_w32-36af842e.pth'
TEST:
  FLIP_TEST: True
  IMAGES_PER_GPU: 1
  MODEL_FILE: '' 
  SCALE_FACTOR: [1]
  NMS_THRE: 0.05
  NMS_NUM_THRE: 8
  KEYPOINT_THRESHOLD: 0.01
  ADJUST_THRESHOLD: 0.05
  MAX_ABSORB_DISTANCE: 75
  GUASSIAN_KERNEL: 6
  DECREASE: 0.9
RESCORE:
  VALID: True
  MODEL_FILE: 'model/rescore/final_rescore_coco_kpt.pth'
